# Superfan Default Configuration

# IPMI Settings
ipmi:
  # No configuration needed for local IPMI access
  # For remote systems, uncomment and configure:
  # host: 192.168.1.100
  # username: ADMIN
  # password: ADMIN

# Temperature Thresholds (in Celsius)
temperature:
  critical_max: 85  # Emergency threshold - will set fans to 100%
  warning_max: 75   # Warning threshold - will increase fan speed
  target: 60        # Desired operating temperature
  hysteresis: 3     # Temperature change required for speed adjustment

# Fan Control Settings
fans:
  polling_interval: 30      # Seconds between temperature checks during normal operation
  monitor_interval: 5       # Faster polling interval when monitoring (seconds)
  min_speed: 30            # Starting point for learning (will be updated by learning mode)
  max_speed: 100           # Maximum fan speed percentage
  ramp_step: 2             # Maximum fan speed change per interval
  
  # Hardware Fan Control Zones
  zones:
    chassis:  # Zone 0: Controls FAN1-5 as a group
      enabled: true
      curve:
        - [0, 30]    # [temp_delta, fan_speed]
        - [10, 45]
        - [20, 60]
        - [30, 75]
        - [40, 90]
        - [50, 100]
      # All system temperatures that affect chassis cooling
      sensors:
        - System Temp
        - Peripheral Temp
        - P1_DIMM*
        - NVMe_*
        - M2_SSD*
        
    cpu:  # Zone 1: Controls FANA (CPU fan)
      enabled: true
      curve:
        - [0, 30]
        - [5, 40]
        - [10, 50]
        - [15, 60]
        - [20, 70]
        - [25, 80]
        - [30, 90]
        - [35, 100]
      # CPU-specific temperatures
      sensors:
        - CPU Temp
        - CPU_VRM Temp
        - SOC_VRM Temp
        - VRMABCD Temp
        - VRMEFGH Temp

# Safety Settings
safety:
  watchdog_timeout: 30    # Seconds before watchdog triggers
  min_temp_readings: 3    # Minimum required readings for reliability
  restore_on_exit: true   # Restore BMC control on program exit
  emergency_timeout: 60   # Seconds before exiting emergency state if temps normal
  verify_commands: true   # Enable command response validation
  min_working_fans: 1     # Minimum number of working fans required
  
# Logging Configuration
logging:
  level: INFO
  file: superfan.log
  max_size: 10MB
  backup_count: 3
