# Superfan Default Configuration

# IPMI Settings
ipmi:
  # No configuration needed for local IPMI access
  # For remote systems, uncomment and configure:
  # host: 192.168.1.100
  # username: ADMIN
  # password: ADMIN

# Global Temperature Settings
temperature:
  hysteresis: 3     # Temperature change required for speed adjustment

# Fan Control Settings
fans:
  polling_interval: 60      # Seconds between temperature checks during normal operation
  monitor_interval: 30      # Faster polling interval when monitoring (seconds)
  ramp_step: 5             # Maximum fan speed change per interval

  # Board-specific parameters (populated by learning phase)
  board_config:
    # Default values for new installations
    min_speed: 20          # Minimum safe fan speed
    max_speed: 100         # Maximum fan speed
    
    # Fan speed steps and RPM ranges (populated during learning)
    speed_steps:           # H12 board speed steps
      low:
        threshold: 12.5    # 0x20 step (12.5%)
        rpm_ranges:
          chassis:
            min: 840      # FAN2-4 at 0x20
            max: 980      # FAN1 at 0x20
          cpu:
            min: 1960     # FANA at 0x20
            max: 2100     # Max at 0x20
      medium:
        threshold: 25      # 0x40 step (25%)
        rpm_ranges:
          chassis:
            min: 980      # FAN2-4 at 0x40
            max: 1260     # FAN1/5 at 0x40
          cpu:
            min: 2940     # FANA at 0x40
            max: 3100     # Max at 0x40
      high:
        threshold: 37.5    # 0x60 step (37.5%)
        rpm_ranges:
          chassis:
            min: 1400     # FAN2-4 at 0x60
            max: 1820     # FAN5 at 0x60
          cpu:
            min: 3500     # FANA at 0x60
            max: 3640     # Max at 0x60
      full:
        threshold: 100     # 0xFF step (100%)
        rpm_ranges:
          chassis:
            min: 980      # FAN2-4 at 0xFF
            max: 1260     # FAN5 at 0xFF
          cpu:
            min: 3500     # FANA at 0xFF
            max: 3640     # Max at 0xFF
            
    # Temperature response characteristics (populated during learning)
    thermal_response:
      chassis:  # System and peripheral temperature response
        low:    # Response at low speed
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        medium:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        high:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        full:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
      cpu:     # CPU and VRM temperature response
        low:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        medium:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        high:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
        full:
          initial_temp: null
          final_temp: null
          temp_change: null
          time_to_stable: null
  
  # Hardware Fan Control Zones
  zones:
    chassis:  # Zone 0: Controls FAN1-5 as a group
      enabled: true
      # H12 Fan RPM ranges at different speed steps:
      # 0xFF (100%):  FAN1=1120, FAN2-4=980, FAN5=1260
      # 0x60 (37.5%): FAN1=1680, FAN2-4=1400, FAN5=1820
      # 0x40 (25%):   FAN1=1260, FAN2-4=980, FAN5=1260
      # 0x20 (12.5%): FAN1=980, FAN2-4=840, FAN5=1260
      critical_max: 75  # Emergency threshold - will set fans to 100%
      warning_max: 65   # Warning threshold - will increase fan speed
      target: 55        # Desired operating temperature
      curve:
        - [0, 20]    # At target temp (55°C)
        - [5, 40]    # 5°C over target -> 40%
        - [10, 60]   # 10°C over target -> 60%
        - [15, 80]   # 15°C over target -> 80%
        - [20, 100]  # 20°C over target -> 100%
      # All system temperatures that affect chassis cooling
      sensors:
        - System Temp
        - Peripheral Temp
        - P1_DIMM*
        - NVMe_*
        - M2_SSD*
        
    cpu:  # Zone 1: Controls FANA (CPU fan)
      enabled: true
      # H12 CPU fan (FANA) RPM ranges at different speed steps:
      # 0xFF (100%):  3500 RPM
      # 0x60 (37.5%): 3640 RPM
      # 0x40 (25%):   2940 RPM
      # 0x20 (12.5%): 1960 RPM
      critical_max: 85  # Emergency threshold - will set fans to 100%
      warning_max: 75   # Warning threshold - will increase fan speed
      target: 65        # Desired operating temperature
      curve:
        - [0, 20]    # At target temp (65°C)
        - [5, 40]    # 5°C over target -> 40%
        - [10, 60]   # 10°C over target -> 60%
        - [15, 80]   # 15°C over target -> 80%
        - [20, 100]  # 20°C over target -> 100%
      # CPU-specific temperatures
      sensors:
        - "CPU* Temp"
        - "*CPU*VRM* Temp"
        - "*SOC*VRM* Temp"
        - "*VRM* Temp"

# Safety Settings
safety:
  watchdog_timeout: 90    # Seconds before watchdog triggers (1.5x polling_interval)
  min_temp_readings: 2    # Minimum required readings for reliability
  restore_on_exit: true   # Restore BMC control on program exit
  emergency_timeout: 60   # Seconds before exiting emergency state if temps normal
  verify_commands: true   # Enable command response validation
  min_working_fans: 1     # Minimum number of working fans required
  
# Logging Configuration
logging:
  level: DEBUG
  file: superfan.log
  max_size: 10MB
  backup_count: 3
