# Superfan Default Configuration

# IPMI Settings
ipmi:
  # No configuration needed for local IPMI access
  # For remote systems, uncomment and configure:
  # host: 192.168.1.100
  # username: ADMIN
  # password: ADMIN

# Global Temperature Settings
temperature:
  hysteresis: 3     # Temperature change required for speed adjustment

# Fan Control Settings
fans:
  polling_interval: 60      # Seconds between temperature checks during normal operation
  monitor_interval: 30      # Faster polling interval when monitoring (seconds)
  min_speed: 20            # Minimum fan speed (increased for stability)
  max_speed: 100           # Maximum fan speed percentage
  ramp_step: 5             # Maximum fan speed change per interval
  
  # Hardware Fan Control Zones
  zones:
    chassis:  # Zone 0: Controls FAN1-5 as a group
      enabled: true
      # Fan RPM ranges:
      # Chassis fans: 1000-2000 RPM
      critical_max: 75  # Emergency threshold - will set fans to 100%
      warning_max: 65   # Warning threshold - will increase fan speed
      target: 55        # Desired operating temperature
      curve:
        - [0, 20]    # At target temp (55°C)
        - [5, 40]    # 5°C over target -> 40%
        - [10, 60]   # 10°C over target -> 60%
        - [15, 80]   # 15°C over target -> 80%
        - [20, 100]  # 20°C over target -> 100%
      # All system temperatures that affect chassis cooling
      sensors:
        - System Temp
        - Peripheral Temp
        - P1_DIMM*
        - NVMe_*
        - M2_SSD*
        
    cpu:  # Zone 1: Controls FANA (CPU fan)
      enabled: true
      # CPU fan: 2500-3800 RPM
      critical_max: 85  # Emergency threshold - will set fans to 100%
      warning_max: 75   # Warning threshold - will increase fan speed
      target: 65        # Desired operating temperature
      curve:
        - [0, 20]    # At target temp (65°C)
        - [5, 40]    # 5°C over target -> 40%
        - [10, 60]   # 10°C over target -> 60%
        - [15, 80]   # 15°C over target -> 80%
        - [20, 100]  # 20°C over target -> 100%
      # CPU-specific temperatures
      sensors:
        - CPU Temp
        - CPU_VRM Temp
        - SOC_VRM Temp
        - VRMABCD Temp
        - VRMEFGH Temp

# Safety Settings
safety:
  watchdog_timeout: 90    # Seconds before watchdog triggers (1.5x polling_interval)
  min_temp_readings: 2    # Minimum required readings for reliability
  restore_on_exit: true   # Restore BMC control on program exit
  emergency_timeout: 60   # Seconds before exiting emergency state if temps normal
  verify_commands: true   # Enable command response validation
  min_working_fans: 1     # Minimum number of working fans required
  
# Logging Configuration
logging:
  level: DEBUG
  file: superfan.log
  max_size: 10MB
  backup_count: 3
