# Superfan Default Configuration

# IPMI Settings
ipmi:
  # No configuration needed for local IPMI access
  # For remote systems, uncomment and configure:
  # host: 192.168.1.100
  # username: ADMIN
  # password: ADMIN

# Global Temperature Settings
temperature:
  hysteresis: 3     # Temperature change required for speed adjustment

# Fan Control Settings
fans:
  polling_interval: 60      # Seconds between temperature checks during normal operation
  monitor_interval: 30      # Faster polling interval when monitoring (seconds)
  min_speed: 5             # Minimum fan speed (matches IPMI validation threshold)
  max_speed: 100           # Maximum fan speed percentage
  ramp_step: 5             # Maximum fan speed change per interval (increased for stability)
  
  # Hardware Fan Control Zones
  zones:
    chassis:  # Zone 0: Controls FAN1-5 as a group
      enabled: true
      # Fan RPM ranges:
      # Group 1 (FAN1, FAN5): 1400-1820 RPM
      # Group 2 (FAN2-4): 1120-1400 RPM
      # Temperature thresholds specific to chassis zone
      critical_max: 75  # Emergency threshold - will set fans to 100%
      warning_max: 65   # Warning threshold - will increase fan speed
      target: 55        # Desired operating temperature
      curve:
        - [0, 5]     # At target temp (55°C)
        - [5, 30]    # 5°C over target -> 30%
        - [10, 50]   # 10°C over target -> 50%
        - [15, 70]   # 15°C over target -> 70%
        - [20, 85]   # 20°C over target -> 85%
        - [25, 100]  # 25°C over target -> 100%
      # All system temperatures that affect chassis cooling
      sensors:
        - System Temp
        - Peripheral Temp
        - P1_DIMM*
        - NVMe_*
        - M2_SSD*
        
    cpu:  # Zone 1: Controls FANA (CPU fan)
      enabled: true
      # Temperature thresholds specific to CPU zone
      critical_max: 85  # Emergency threshold - will set fans to 100%
      warning_max: 75   # Warning threshold - will increase fan speed
      target: 65        # Desired operating temperature
      curve:
        - [0, 5]
        - [5, 30]
        - [10, 45]
        - [15, 60]
        - [20, 70]
        - [25, 80]
        - [30, 90]
        - [35, 100]
      # CPU-specific temperatures
      sensors:
        - CPU Temp
        - CPU_VRM Temp
        - SOC_VRM Temp
        - VRMABCD Temp
        - VRMEFGH Temp

# Safety Settings
safety:
  watchdog_timeout: 90    # Seconds before watchdog triggers (1.5x polling_interval)
  min_temp_readings: 2    # Minimum required readings for reliability
  restore_on_exit: true   # Restore BMC control on program exit
  emergency_timeout: 60   # Seconds before exiting emergency state if temps normal
  verify_commands: true   # Enable command response validation
  min_working_fans: 1     # Minimum number of working fans required
  
# Logging Configuration
logging:
  level: DEBUG
  file: superfan.log
  max_size: 10MB
  backup_count: 3
