# Superfan Default Configuration

# IPMI Settings
ipmi:
  # No configuration needed for local IPMI access
  # For remote systems, uncomment and configure:
  # host: 192.168.1.100
  # username: ADMIN
  # password: ADMIN

# Temperature Thresholds (in Celsius)
temperature:
  critical_max: 85  # Emergency threshold - will set fans to 100%
  warning_max: 75   # Warning threshold - will increase fan speed
  target: 60        # Desired operating temperature - verified through testing
  hysteresis: 3     # Reduced from 5 for more responsive control

# Fan Control Settings
fans:
  polling_interval: 30      # Seconds between temperature checks during normal operation
  monitor_interval: 5       # Faster polling interval when monitoring (seconds)
  min_speed: 10            # Reduced from 30 based on testing (1260 RPM stable)
  max_speed: 100           # Maximum fan speed percentage
  ramp_step: 2             # Maximum fan speed change per interval
  
  # Fan Zones Configuration
  zones:
    nvme:
      enabled: true
      sensors: ["NVMe_*"]  # Pattern to match NVMe temperature sensors
      curve:
        - [0, 30]    # [temp_delta, fan_speed]
        - [5, 40]
        - [10, 50]
        - [15, 60]
        - [20, 70]
        - [25, 80]
        - [30, 90]
        - [35, 100]

    cpu:
      enabled: true
      sensors: ["CPU Temp", "CPU_VRM Temp"]
      curve:
        - [0, 10]     # Base speed 10% (1260 RPM) - verified stable
        - [5, 15]     # Small increase at 5°C over target
        - [10, 20]    # Gradual increase as temp rises
        - [15, 30]
        - [20, 50]    # More aggressive scaling at higher deltas
        - [25, 70]
        - [30, 90]
        - [35, 100]   # Full speed at 35°C over target
    
    system:
      enabled: true
      sensors: ["System Temp", "Peripheral Temp"]
      curve:
        - [0, 30]
        - [10, 45]
        - [20, 60]
        - [30, 75]
        - [40, 90]
        - [50, 100]

# Safety Settings
safety:
  watchdog_timeout: 30    # Seconds before watchdog triggers
  min_temp_readings: 3    # Minimum required readings for reliability
  restore_on_exit: true   # Restore BMC control on program exit
  emergency_timeout: 60   # Seconds before exiting emergency state if temps normal
  verify_commands: true   # Enable command response validation
  min_working_fans: 1     # Minimum number of working fans required
  
# Logging Configuration
logging:
  level: INFO
  file: superfan.log
  max_size: 10MB
  backup_count: 3
